* Вступ
Привіт, мене звати Тетяна Казарян. Я викладач англійської мови і запрошую вас вчити англійську за цим курсом. Це й курс для тих, хто не знає англійську, добрячє забув її або не було досягнуто помітних успіхів раніше і розрахований на самостійне вивчення. В результаті проходження курсу, ви отримаєте базові навички англійської, які дозволять вам розпочати спілкування англійською, наприклад не розгубитись в аеропорту, магазині, готелі, спитати дорогу, коротше, вас там зрозуміють. Інша ціль - дати вам той мінімум, з яким ви зможете опанувати більш складні рівні англійської або методики навчання.
Чому я вирішила створити щє один курс? Більшість книг та курсів на пострадянському просторі грішать тим, що дають чимало граматики, але мало тої практики, яка дозволить розпочати спілкуватись. Одна з причин, це упор на граматику, а не на спілкування. Чому так? Бо так історично склалося. Донедавна вміння спілкуватись, особливо з іноземцями, не мало попиту. Як би там не було, це більше шкодить, бо виникає *перегруз граматикою* і коли справа доходить до спілкування людина губиться в усіх цих правилах. По-друге, граматика не до кінця відображає реальне спілкування. Це не значить, що граматика не потрібна. Вона потрібна. Але, як показує моя практика, потрібно зробити упор на розвитик навиків спілкування, а не знання граматичних тонкощів.
Я вже не перший рік навчаю англійської, працювала з різними джерелами і методиками і тому прийшла до висновку, що кращє зробити свою. А сучасні технології дозволяють поширити її як можна більшій аудиторії.
Проходячи цей курс ви взнаєте базову граматику і базовий словниковий запас. Проходити курс можна на Youtube або у спеціальному додатку, посилання на який ви знайдете у описі відео. Що додаток дає в порівнянні з Ютубом? Працюючи з додатком ви не тільки диветесь відео, але і відразу практикуєте навички вимови і письма, що дуже сильно покращує засвоєння матеріалу. Разом з додатком для курсу я раджу використовувати додаток, розроблений для вивчення слів - Word Dolphin, який дозволяє вивчити і не забути слова. Посилання на нього теж у описі.
Тепер про дуже важливий момент. Вчитель - не чудотворець! В Новому Заповіті є епізод, коли Бог дав апостолам дар говорити іншими мовами. Тобто, за день до того вони не мовами не володіли, а тут почали. Я так не вмію :( Тому ваша англійська - це результат ваших зусиль. Вчитель може тільки певним чином подавати матеріал, так щоб його було легше засвоїти. Але результат залежить від вашої щоденної праці. Саме так, мова йде про щоденну працю. Так само це стосується фітнесу, водіння автівки і т.д. Скільки грошей ви б не платили, знання неможливо вкласти, їх можна тільки самостійно напрацювати. І тільки після самостійної практики, за кілька місяців ви відчуєте результат.
Готові до цього? То розпочнемо!
